'\" t
.\"     Title: dia
.\"    Author: Fredrik Hallenberg <hallon@lysator.liu.se>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 2004-11-26
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "DIA" "1" "2004\-11\-26" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dia \- un programme de dessin de diagrammes
.SH "SYNOPSIS"
.HP \w'\fBdia\fR\ 'u
\fBdia\fR [\fB\-c\fR] [\fB\-\-credits\fR] [\fB\-e\ \fR\fB\fISORTIE\fR\fR] [\fB\-\-export=\fR\fB\fISORTIE\fR\fR] [\fB\-L\ \fR\fB\fICALQUE,CALQUE,\&.\&.\&.\fR\fR] [\fB\-\-show\-layers=\fR\fB\fICALQUE,CALQUE,\&.\&.\&.\fR\fR] [\fB\-h\fR] [\fB\-\-help\fR] [\fB\-n\fR] [\fB\-\-nosplash\fR] [\fB\-s\ \fR\fB\fIWxH\fR\fR] [\fB\-\-size=\fR\fB\fIWxH\fR\fR] [\fB\-t\ \fR\fB\fIFORMAT\fR\fR] [\fB\-\-filter=\fR\fB\fIFORMAT\fR\fR] [\fB\-v\fR] [\fB\-\-version\fR] [file\ \&.\&.\&.]
.SH "DESCRIPTION"
.PP
\fBDia\fR
est utilisé pour créer des diagrammes\&. Dia possède des outils de base, comme les lignes et les boîtes, mais peut également charger dynamiquement des
\fIfeuilles\fR\&. Une feuille est une collection d\*(Aqoutils utilisés dans un certain type de diagramme\&.
.PP
La plupart des objets de diagramme dans
\fBDia\fR
ont des
\fIpoints de connexion\fR\&. Les lignes peuvent être connectées à ces points de connexion, et par ce moyen des structures de graphe peuvent être mises en forme\&. Lorsque les objets sont déplacés, ou leurs dimensions changées, les connexions suivent ces objets\&.
.PP
les diagrammes dessinés avec
\fBDia\fR
peuvent être exportés dans le format PostScript\&.
.SH "OPTIONS"
.PP
\fBDia\fR
accepte les options suivantes :
.PP
\fB\-c\fR \fB\-\-credits\fR
.RS 4
Affiche la liste des attributions et quitte\&.
.RE
.PP
\fB\-e \fR\fB\fISORTIE\fR\fR \fB\-\-export=\fR\fB\fISORTIE\fR\fR
.RS 4
Exporte le fichier chargé dans SORTIE et quitte\&.
.RE
.PP
\fB\-h\fR \fB\-\-help\fR
.RS 4
Affiche la liste de toutes les options de la ligne de commande\&.
.RE
.PP
\fB\-n\fR \fB\-\-nosplash\fR
.RS 4
N\*(Aqaffiche pas l\*(Aqécran de lancement\&.
.RE
.PP
\fB\-s \fR\fB\fILxH\fR\fR \fB\-\-size=\fR\fB\fILxH\fR\fR
.RS 4
Exporte le fichier chargé dans la largeur et/ou la hauteur décimale donnée\&. Il est possible de ne sélectionner que la hauteur ou la largeur\&. P\&.ex\&.
\fB\-\-size=\fR\fB\fI520x\fR\fR
exporte une image de 520 pixels largeur, alors que
\fB\-\-size=\fR\fB\fIx900\fR\fR
exporte une image de 900 pixels de hauteur\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
Cette option n\*(Aqest actuellement implémentée que pour le filtre d\*(Aqexport PNG\&.
.sp .5v
.RE
.RE
.PP
\fB\-L \fR\fB\fICALQUE,CALQUE,\&.\&.\&.\fR\fR \fB\-\-show\-layers=\fR\fB\fICALQUE,CALQUE,\&.\&.\&.\fR\fR
.RS 4
N\*(Aqinclue que les calques spécifiés lors de l\*(Aqexportation\&. Les calques peuvent être spécifiés par leur nom, leur numéro, ou une étandue numérique X\-Y de calques\&. \-\-show\-layers=background,2\-5 montre les calques nommés background et les calques 2 à 5, \-\-show\-layers=2\- montre les calques 2 et supérieurs\&.
.RE
.PP
\fB\-t \fR\fB\fIFORMAT\fR\fR \fB\-\-export\-to\-format=\fR\fB\fIFORMAT\fR\fR
.RS 4
Exporte le fichier chargé dans le FORMAT et quitte\&. Les FORMATS D\*(AqEXPORTATION sont décrits ci\-dessous\&.
.RE
.PP
\fB\-v\fR \fB\-\-version\fR
.RS 4
Affiche la version de
\fBdia\fR
et quitte\&.
.RE
.SH "FORMATS D'EXPORTATION"
.PP
Les formats d\*(Aqexportation suivants sont supportés par
\fBdia\fR\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
cgm
(Computer Graphics Metafile, ISO 8632)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
dia
(diagram Dia natif)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
dxf
(Drawing Interchange File)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
eps
ou
eps\-builtin
ou
eps\-pango
(PostScript encapsulé)
.sp
Les spécifications de format
eps
et
eps\-pango
utilisent toutes\-deux le rendu de fontes de la bibliothèque Pango, alors que
eps\-builtin
utilise le rendu de fontes spécifique de dia\&. Si vous avez des problèmes avec le rendu de Pango, p\&.ex\&. avec Unicode, utilisez
eps\-builtin
à la place\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
fig
(format XFig)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
mp
(macros TeX MetaPost)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
plt
or
hpgl
(HP Graphics Language)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
png
(Portable Network Graphics)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
shape
(Fichier Dia Shape)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
svg
(Scalable Vector Graphics)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
tex
(macros TeX PSTricks)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
wpg
(WordPerfect Graphics)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
wmf
(Windows MetaFile)
.RE
.SH "FICHIERS"
.PP
\fBdia\fR
crée un répertoire
\&.dia
dans le répertoire \(Fo home \(Fc de l\*(Aqutilisateur, contenant différents fichiers qui enregistrent ses préférences\&. Pour initialiser
\fBdia\fR
dans son comportement par défaut, il suffit d\*(Aqeffacer les fichiers suivants :
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
defaults\&.dia: contient les valeurs par défaut des éléments (format XML)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
diarc: garde les préférences de
\fBdia\fR
(ASCII)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
history: garde la liste des derniers diagrammes édités (ASCII)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
menurc: contient une emprunte de carte d\*(Aqaccélération automatisée (Lisp)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
persistence: contient les information d\*(Aqinterface graphique, p\&.ex\&. les fenêtres ouvertes (XML)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
pluginrc: la liste des plugins chargés (XML)\&.
.RE
.SH "VOIR AUSSI"
.PP
\m[blue]\fBPango\fR\m[]\&\s-2\u[1]\d\s+2
.PP
X (1)
.PP
xfig (1)
.PP
inkscape (1)
.SH "COPYRIGHT"
.PP
Copyright 1999 Alexander Larsson\&.
.PP
Permission to use, copy, modify, and distribute this software and its documentation for any purpose and without fee is hereby granted, provided that the above copyright notice appear in all copies and that both that copyright notice and this permission notice appear in supporting documentation\&.
.SH "AUTEURS"
.PP
Alexander Larsson
.PP
This manual was written by
Fredrik Hallenberg\&.
.SH "TRADUCTION"
.PP

Thomas Harding
.SH "AUTHORS"
.PP
\fBFredrik Hallenberg\fR <\&hallon@lysator\&.liu\&.se\&>
.RS 4
Author.
.RE
.PP
\fBW\&. Borgert\fR <\&debacle@debian\&.org\&>
.RS 4
Author.
.RE
.PP
\fBAlan Horkan\fR <\&horkana@tcd\&.ie\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 1999, 2004 Fredrik Hallenberg, W. Borgert, Alan Horkan
.br
.SH "NOTES"
.IP " 1." 4
Pango
.RS 4
\%http://www.pango.org/
.RE
